# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZEGOCallDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ZEGOCallDemo
  pod 'ZIM','>=2.1.1'
  pod 'ZegoExpressEngine'

end
