# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZEGOCallDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ZEGOCallDemo
  pod 'ZegoExpressEngine'
  
  pod 'FirebaseAuth'
  pod 'GoogleSignIn'
  pod 'Firebase/Database'
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Messaging'
  pod 'Firebase/Functions'

end
